### PR TITLE
fix: update priority handling

### LINKED ISSUE #38: Priority config is not respected properly
There are currently a few issues with how priority config is handled. 
- LSP priorities are not read properly and cause fastaction to error out
- Priorities are not parsed first, leaving them to be skipped if other actions claim the relevant keys first
- Priorities are sorted to the end of the list instead of the beginning

Repro:
1. Configure plugin with some non-LSP priorities in the config
2. Configure plugin with some LSP priorities in the config
3. Open code actions at a relevant diagnostic

```lua
{
  "chaitanyabsprip/fastaction.nvim",
  opts = {
    priority = {
      eslint = {
        { key = "f", order = 1, pattern = "fix this" },
        { key = "a", order = 2, pattern = "fix all" },
      },
      ["null-ls"] = {
        { key = "S", order = 4, pattern = "add.*to.*~/%.config/cspell%.json" },
        { key = "s", order = 3, pattern = "add.*to.*cspell%.json" },
      },
    },
  },
}
```

Expected:
Image

Actual:
```
Error executing vim.schedule lua callback: .../share/nvim/lazy/fastaction.nvim/lua/fastaction/init.lua:187: bad argument #1 to 'match' (string expected, got nil)
stack traceback:
	[C]: in function 'match'
	.../share/nvim/lazy/fastaction.nvim/lua/fastaction/init.lua:187: in function 'sort_items'
	.../share/nvim/lazy/fastaction.nvim/lua/fastaction/init.lua:22: in function 'select'
	...lar/neovim/0.11.1/share/nvim/runtime/lua/vim/lsp/buf.lua:1211: in function 'on_code_action_results'
	...lar/neovim/0.11.1/share/nvim/runtime/lua/vim/lsp/buf.lua:1255: in function 'handler'
	.../neovim/0.11.1/share/nvim/runtime/lua/vim/lsp/client.lua:682: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

### PR DESCRIPTION
**Pull request by wesrupert**
Fixes #38.

- LSP priorities listed in the config were merged as a list-of-lists, resulting in the configs being dropped during priority generation. Flatten lists to support lsp priorities properly.
- Priority keys weren't actually evaluated in a priority fashion, often leaving them unable to reserve the designated key by the time an action was evaluated. Separate the priority/non-priority get_action_config functions and perform a pre-pass with priority keys to ensure the reserved keys are taken and not left up to the original actions order.
- Priorities are sorted by lower-first, but non-priority options were being defaulted to priority 0 instead of inf. Update sort heuristic to place priority items at top of list.

Note: I moved a few list maps over to [`vim.iter`](https://neovim.io/doc/user/lua.html#vim.iter); if you would prefer to target older versions than 0.10, I can rewrite these with legacy `table.map` implementations instead.

### CODE REVIEW

File: lua/fastaction/init.lua [hunk 1]
```diff
@@ -70,47 +70,74 @@ function M.select(items, opts, on_choice)
...
-            name = opts.format_item(item),
-            right_section = conf.format_right_section and conf.format_right_section(item) or '',
-        }
-        local match = assert(
-            keys.get_action_config {
+    ---Get priority configs first to reserve keys, then try remaining heuristics first-come-first-serve.
+    ---@param items_to_process any[] Arbitrary items
+    ---@param check_priority? boolean Iff true check priorities (and only priorities)
+    ---@return any[] remaining_items Remaining items that were not processed
+    local get_action_configs = function (items_to_process, check_priority)
```
Comment (wesrupert) [inline lua/fastaction/init.lua:91]: Making this a local function originally let me update the closure to manage `remaining_items` internally. I removed the side effect partway through writing, so this doesn't _need_ to stay inside `M.select`. I can move this to `m` if preferred.

Comment (Chaitanyabsprip) [reply lua/fastaction/init.lua:91]: Yes, please move that to `m` namespace

**Comment by Chaitanyabsprip** [comment]
Can you also please update the types wherever required

**Comment by wesrupert** [comment]
Moved `get_action_configs` to `m` scope and added type signature. Were there other types you saw that I missed?
